version: '3.8'

services:
  web-monitor:
    build: .
    container_name: asentrx_web_monitor_instance
    env_file:
      - .env
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"